index:
    path: /
    controller: App\Controller\DefaultController::index

latest_runs:
    path: /latest_runs
    controller: App\Controller\DefaultController::latestRuns

world_records:
    path: /world_records
    controller: App\Controller\DefaultController::worldRecords
